apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- adguard-home
- davmail
- descheduler
- etherpad
- goldilocks
- home-assistant
- metrics-server
- ocis
- portainer
- privatebin
- servarr
- tailscale-operator
- vaultwarden
- vpa
