apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- davmail
- descheduler
- etherpad
- goldilocks
- jellyfin
- metrics-server
- ocis
- portainer
- privatebin
- tailscale-operator
- vpa
