allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1                                                                                                                                                               metadata:
        name: longhorn
        annotations:                                                                                                                                                                                  storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true                                                                                                                                                                  reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:                                                                                                                                                                                   numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""                                                                                                                                                                              fsType: "ext4"
        dataLocality: "disabled"
        unmapMarkSnapChainRemoved: "ignored"                                                                                                                                                        disableRevisionCounter: "true"
        dataEngine: "v1"
    storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-05-15T08:59:51Z"
  name: longhorn
  resourceVersion: "10809"
  uid: 65c09b03-2539-4dd1-a54d-2fade8041fe6
parameters:
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete 
