apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: lldap
type: Opaque
stringData:
    jwtSecret: ENC[AES256_GCM,data:YOtKDjwrJdMJgQxiBFH/DI0JwElRbaB5OQZQf8BFTXB9oYQLtZdFr4Lbs20p+9XX6TayERij3jMydw==,iv:A8gC2OaqNAqDipOwOsLR9RlBUNsp6Gjm97b1s3iZOR4=,tag:Bi/18qNkrJw++bQfarRHtg==,type:str]
    ldapUserPass: ENC[AES256_GCM,data:ym/DxwU5+VumMv+PZPpgeQO8+PHAdtpfXC8xT7bw2Td73kWmwRsiaOdxS+rvT+zC4g==,iv:pKBEk1vEXy2LagijlW3CWSRpf5ZuliHKjwU3tXVD1tw=,tag:zq1ZqXZdgTSmagnBwLtd9A==,type:str]
    keySeed: ENC[AES256_GCM,data:BB/AR9y7hwMf7oO+VeRkEoUmrS6bCsb1mK2R/dr6508rQA4XMmN7jUn8z6+LyrCrf0n9,iv:NCxz6PwR1LZKuNfrrkl/9KDxZFaJzcMK/Ok7HNJlQ9g=,tag:odsZfW781rhtBZJWKZndRQ==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YS8wTjF2QTNLTVFJcHBy
            eXI1WHh1S295U0dKeVZSOSsyVGkrOW9lZEF3CmVKaC9NbHBzSDRoRFJLZnNBdmYx
            K1JLTlYwemVqQkdMclRJWTMxYTRGVzAKLS0tIG91bmpnZlpYeDhuRkh2OVdURnJR
            ODRWd0JNWWIrUDIrUkNPWDlKb0t0ZzQKcgRg1fApBLTFbavrkjAnBqmnhAQgp4VC
            kt4GAMKad5jXh1CKF2eOjTScH8TjT2pRrkTt8r8sF3z9MZNhfu9B+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T15:45:26Z"
    mac: ENC[AES256_GCM,data:UxMGwaJspfLj12c3cP1YwsJWoLIkJiM5MgCuCokjNl4Lrj7EyqB2ixfUCmXbHlcNqVuTjsU3pa/a+hWD58asigPejsHVI6yGlF35yG3Sx4QMcy9wHY8OzkXtWv/J7NH242C6IzidMUJ/5bimUH/z0ONFG67/ImGbrYkEc1JcFNo=,iv:HIDPiOnZNMhx4lxOvBJPKA++F9x1PMYjWq9525wx+zM=,tag:vEUmaxZSHIPcZeOW+oOVXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
