apiVersion: v1
kind: Secret
metadata:
    name: etherpad
    namespace: etherpad
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:gPGk1uzaSvRyV+ZJZ3dpGiyqAUDe75hf3wYiAWlaTdrPb45b2iWUovwy8Qov7QFeCnFDjJNFtnj3oeId,iv:jkQKtlS1NGD+iM4U9dzHNQJ1Xa9qC+JAgTfuwOFWshU=,tag:5S1cnyXzmRes1NBLP8PQDw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YS8wTjF2QTNLTVFJcHBy
            eXI1WHh1S295U0dKeVZSOSsyVGkrOW9lZEF3CmVKaC9NbHBzSDRoRFJLZnNBdmYx
            K1JLTlYwemVqQkdMclRJWTMxYTRGVzAKLS0tIG91bmpnZlpYeDhuRkh2OVdURnJR
            ODRWd0JNWWIrUDIrUkNPWDlKb0t0ZzQKcgRg1fApBLTFbavrkjAnBqmnhAQgp4VC
            kt4GAMKad5jXh1CKF2eOjTScH8TjT2pRrkTt8r8sF3z9MZNhfu9B+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T02:20:01Z"
    mac: ENC[AES256_GCM,data:Sha2m1bIVa0l7uCBi/RaotY5zzKEIeHpJ/4xiCJCJ/y7dD3QPVJcou6j6Uq6FWkKTaBfY25gLpw05VfLU3HzOZeGJtocPt7DxAztSIqMADqqhHMdpQAI+WfZIGxa0ip4DwIrKF6Za0mByZvJizButmXsPKthCcIvVxOK8K08OAE=,iv:nYngCmyUSOvLFxwaXdUZK/WnHUqGmDJdjMvvf8Og/VQ=,tag:JLCn4jf6GIakm+XdJ0EpMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
