apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:4KGwxqiBNnVRgjfDV5E42lSX+cZ7g7JkDbhYUPKJL9qCICaSKWoBDpHzEhJO4EIolO6MEBQzaf5wNT6gf+xVSfpDNjG/r08LlBw=,iv:p5wZuufD9ID3i2CGAc7ggonm5GV9l6DKUrjxjQDErcA=,tag:GJ/au6CW+MUL+neyNcnnTQ==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYlkrWjZDTzZmVmhOSEFW
            UTQ2YVJqck5wR3pWZkhDNmdUdnZmM0ZrMkJFCnBNaG5DMWJlMzhndXpHa0E4NThS
            emRISTl1eHltWTJJelBrVDZlL21RRWcKLS0tIHZGcFRjazlOZVUwNXhpVElEdzBy
            c0JJWWZLSTBzK0hXRnFRb2h1VlNzQnMKM1C3DpYZ4PEnRznIhOUGs2y4/vJIZD3w
            pTZVq1I1y+l0y8+CqeZkl9RrplM91kXoZHfY5Eq1yGHV5qZuh25GZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-22T12:50:35Z"
    mac: ENC[AES256_GCM,data:SbqK/j8oMTA62MOxhUUfH1za/9WOk1B/hinlVDPeuY00iEnvB0kurXhio/DxvYhpYgwvJleu0sJEKKj5M3riBw5WmFsFrOkjyu4aeueS6uIczVqZC9VwxOOy84A3JzQzIgdOMkCeQcaVm4MYxsR5HA1NN4UiEHSwEXZ+56qOpok=,iv:y5W6YHY52cL7AoW3lHFJOkKAQ+xquKR63d/XfBoyxZ4=,tag:BOoCDh/lMWvvh3GF1pqvXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
