apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: ">=24.6.6"
      sourceRef:
        kind: OCIRepository
        name: bitnami
        namespace: flux-system
  values:
    adminRealm: "main"
    production: false
    proxyHeaders: "xforwarded"

    auth:
      adminUser: admin
      existingSecret: secrets
      passwordSecretKey: admin_password

    tls:
      passwordsSecret: secrets

    spi:
      passwordsSecret: secrets

    postgresql:
      auth:
        existingSecret: secrets
        secretKeys:
          userPasswordKey: postgres-user-password
