apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: keycloak
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:M0onuyuCqz8528LPQ4uhnGhIZhcqSrzy6yCcr1s4CpWwFsAf4LhyaUNR4UOM64e8eu0SVk/E,iv:MiAmAwy4Rdg5amo7Wu6e1vPxO6by/5zHZ1fyCPsVVPU=,tag:bQQby+FbB+uxGsUtTZOLCg==,type:str]
    tls-keystore-password: ENC[AES256_GCM,data:36S5ziAgK3yeXeUG4BFUQ/70GHBnRSfcuFSTaEiS3C/OkM8xSG4z95wQjq4zNSGHbxYF6EMFcEJgfopAIBs=,iv:AJB1SyO0ROHPANi7/uLNceCEKl2sXrqw5Eu2tYnks4g=,tag:ufUj5Fg7PaPia7XbvdOHVg==,type:str]
    tls-truststore-password: ENC[AES256_GCM,data:TDg4Dv4D5PsZJWud8JnvPJk0R3L0n7ePw7UQA1DCwJG3uWQyZjKdilKWwyaovLymFVqQgeUYGaZi,iv:1pGiOfIawybY1z6fU4aSSZljfUX0guSjxDSEBUP1EIo=,tag:nAMf/13QlGUTJnE9MqMZQg==,type:str]
    spi-truststore-password: ENC[AES256_GCM,data:ssVZlczWsyhHgR4A7j4wo/Yerb8Ga5ujZli7aGpPcNWOtrgsfES9SsQEEOfl04c3iwXLNJs=,iv:PNxftQOu7Ty6sGdlYnbUD+R6KsKXaVqqAFqY+VlfsQU=,tag:eyst6kUjcdWbQ7xvNzcIsg==,type:str]
    postgres-user-password: ENC[AES256_GCM,data:z2KaOf35dUGULcPhrX7aWj9x/dXtepl8pNgK3kPhW4avO8g3jMMQLGOxx8uAF8YY,iv:zvORdp+Bc4U+ER/ckgNkMadD8PzeI3WNjtAmFmzApOQ=,tag:tM3wy7RbY2lVrrvCJTKGKQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:zWyiaznWrBp5OOz+oPxgOA2L80WDdI+T1XbeSDizWGaKoFnDY90PxOI32A==,iv:qwMBhTL6akkHM2UHI4xmwkbndgZecvnP0hsOAjRJc+E=,tag:J8nFNlQopgglVCqjZKwsdQ==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM0hMS2FvTGxiSWVxdzVk
            VDZTWVhlaGkrdkNHY0ZsdHIrQmNJdHJjVlM4Cis3WVdlczhRYVNsenhoc2JWNTlx
            NlppaVJXRjFMYy91VVVmWTkyQ2VpMUUKLS0tIDc3RTgzRkhxR1JXemlxOTJISlND
            YVk3a0FrZ1hQZVhGQyttTEJYMHFGM2cKQbwpisKI6HSNV/6SIriUCUg8cf+gg2n1
            MPqkGKmBhKuvjgKPu/wgqeFIpQBKgST+h6tBr+fIoebyA1rBltiHPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T13:46:33Z"
    mac: ENC[AES256_GCM,data:qu/gK1ZEnirdBmfk+QnbPZJETg04PAR/uesvradxY9f1LNOmv5xF9BQYmzoNrerYNHfMvPkT+lf/1uw3tYunJzr61CgT2TjfFMXlPTGqHhuwVskc5eZzbGsWs3WIKPplmYrGI27zE70WR1FxSUE2myudcpCCYRg/PJl3y/qTq2I=,iv:Tqo0zcpzHq3vRKiPzVTYXuNxibFLAl9sVYQeKYnDzVY=,tag:PDgJvCEds2IHIQeXEi5iYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
