apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: operator-oauth
    namespace: tailscale-operator
stringData:
    client_id: ENC[AES256_GCM,data:Q6pSJqjCjEgMqKOAgEVZA3FkosPghKp5,iv:W4L20JPxCnKBN6Lafu4QPDhZiOZlbekBy9YFPmjrTM0=,tag:0+dPB/bn5hDwlDz0Xwuc3A==,type:str]
    client_secret: ENC[AES256_GCM,data:qJcwhNDxBKm/nnLGULpoP+NL1tISCI6h/JiiImbNtV55O4AQGeCbCDFgPwZ3czjj+K1mBJ3PH/Hu5V34s7g3NoXRIUIbOZhDtG+6w9oHv9l1se2g2VBU+g==,iv:TTrkdzvZ/SFSOuZnGhXw/Ixka08IU6Jca/KlxXvEnug=,tag:foiMzqWcW8v4VX7WeYJfcw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNU1nYWRPbzl3UkJwNkRR
            T2pQZHdMTnM3OVcrUzRJUFcrYjZNdXJpUURrClhqcmpSMFhpeW1VNTh1WXRaaUhq
            VzMvdGpFQzE3MExvSE0vbmtweWRDMkkKLS0tIGFIQkl2dk9veDlEaWNCUGppN3cw
            NE1FZGxyeTdJT25jOVV6WmpheUxnSjQKiqhJrXwsLx9HiPJDopeUb5NW+hJoRTIO
            4fvwugt646CtC512KANGstvjMNSkcDxeltd2g7mrvcf0mmt0m54b+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T03:43:56Z"
    mac: ENC[AES256_GCM,data:qMs3qNzZWZWBo9NyqkxUleyjcjUWl1h/cNQnuD0a9tZu9xSXVGHC2+I1bHViz8WvJn5Ef/GSCSVpRWeEMnF9ToFuvPE4F+RNrRgvWImShmmYRg0b82FL+qs62Glz91FTsgC9wuoQnpThvV7Vx5ZSBVbbL1l+pfyK7AZ2Ts3/vKA=,iv:P5+D0hdO6Vne5PlK3NJ48ECLDNvm4nRda03mC2jOXY8=,tag:i0p+Ktniyz1QP7d6jZW/Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
