apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: operator-oauth
    namespace: tailscale-operator
data:
    client_id: ENC[AES256_GCM,data:B0nLWRbW7eB7vdOsLkTlHFxMGkpIzp5J,iv:5SrNSCMRj5g3VNLirvG/Oo49DY2iM2zqD+vdBS5juKo=,tag:Yt0m/VoSsPWl9Yx1tKHUqw==,type:str]
    client_secret: ENC[AES256_GCM,data:u550Ts+G+97J1L1eHz/mdG+NdOlQF9n+udsxmZwvwEPhwkY+EsbsMjCF16j42loRsgvUlteGR4VBqjrP6HXlkU1OcS+3xqPvCENAJiPGNzf/lJwY8ydrEA==,iv:styMV/8Zq3NCO+gkxuS81B6vmQzzyIsHiXkMsvaY4e8=,tag:xn4jx3na/ufs4FHC0vr+3g==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUlLTnZpREU1WHBORitQ
            MlErOXBqVDN4NTBGTS9LWFNMVUxOTWtkRXdVCkFYd3hGMUVnM3E2ZENXUUQwWmNM
            ZVVLRXpiZ1NzNHRnbVlESFpQMmF6Y2sKLS0tIEZ2MEhvRk8zak9zR09iN3hNOXdO
            Sm5rVDliTE1QTjc1RlU4anhTWW55ZXMKJvbZlqQf/psspD0fnn+reSVHVNfcO6tF
            4iocW25dHJzJOMa1ZPwWt0kfO5zgOZ1R5IQaZIrV9vcx3S6TFy9qcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T01:48:00Z"
    mac: ENC[AES256_GCM,data:AZVu1EEqZhdT1evZ2EnASh8G0MnHhSVfIaKAvveQef6EemMTiCq41N1fP9iocHj22ydiF0PY5bWG6yQ/PCmq/Iz6/PjlNQY1euUhOT4lLbEOPSrw9UUFFchqghYTPW6EXsZ5zSJH/s0dicgZYwyyub12/cA0wC/lkMP1UTxVlQc=,iv:8Ew2QyMmKsuEZ5A0jQX/c2w0pshGHbjeQeIP7vJOPVU=,tag:+iUIbAhmaTaTw9i3IVn+7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
