apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: operator-oauth
    namespace: tailscale-operator
stringData:
    client_id: ENC[AES256_GCM,data:a7uUzLAi3RJtJBPTUXra6HM=,iv:vLRDxnUpHgV+8Nere4CYVam5k8hSuEHclNG74MSljLQ=,tag:8a56YpWN5Pow+xD2P5w5SQ==,type:str]
    client_secret: ENC[AES256_GCM,data:gl2j6IDYZRshu2Oz+ZWzEP/00RqHuVnC5p4D/s4UfXURNGEKaMHelx5TQdZICm3GzKsQOqoIQS+i7HN/xwLTXw==,iv:vuMuXSg+t8ld436GzbI/+B1WRYGtWgo9oiqdXGnlFK0=,tag:+jgFftY4a3TuvrZaIyAaMw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNU1nYWRPbzl3UkJwNkRR
            T2pQZHdMTnM3OVcrUzRJUFcrYjZNdXJpUURrClhqcmpSMFhpeW1VNTh1WXRaaUhq
            VzMvdGpFQzE3MExvSE0vbmtweWRDMkkKLS0tIGFIQkl2dk9veDlEaWNCUGppN3cw
            NE1FZGxyeTdJT25jOVV6WmpheUxnSjQKiqhJrXwsLx9HiPJDopeUb5NW+hJoRTIO
            4fvwugt646CtC512KANGstvjMNSkcDxeltd2g7mrvcf0mmt0m54b+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T17:56:21Z"
    mac: ENC[AES256_GCM,data:hjacn8nrUIv2Iu2HcWTD6QQY8DIuJoH1q2Lokeh7t88sfvFPw7+wyuGDoFdgT0KrsS6N+z/FlO253iB0ZI8yIpX8zgV2d7n+HUcf853z1axKjbhL5eYHvcfe8cjUQN3io/0tpTdQ3Yk2X8hZzhDl4sejxtr75Xx1eeyAsiag2t0=,iv:Fzceq6juQZzqjUAa6l2aosFr3HV5J/ElK9dfdA1xK5w=,tag:XizT0TwDTalGAt2psBoGjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
