apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: davmail
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/thatfave/davmail-helm/davmail
  ref:
    semver: ">= 0.1.0"
