apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1h
  url: oci://charts.bitnami.com/bitnami/keycloak
  ref:
    semver: ">= 24.6.6"
