apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- davmail.yaml
- descheduler.yaml
- djjudas21.yaml
- fairwinds.yaml
- ocis.yaml
- portainer.yaml
- privatebin.yaml
- redhat-cop.yaml
- tailscale.yaml
