apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- adguard-home.yaml
- davmail.yaml
- fairwinds.yaml
- homarr.yaml
- home-assistant.yaml
- portainer.yaml
- privatebin.yaml
- servarr.yaml
- tailscale.yaml
- tandoor.yaml
- vaultwarden.yaml
