apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- davmail.yaml
- geek-cookbook.yaml
- keycloak.yaml
- kubernetes-sigs.yaml
- ocis.yaml
- portainer.yaml
- privatebin.yaml
- tailscale.yaml
- utkuozdemir.yaml
