apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goldilocks-ingress
  namespace: goldilocks
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: goldilocks-dashboard
      port:
        number: 80
  tls:
  - hosts:
    - goldilocks
