apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:baLcfn5yKChMv7vWZYirqcaDCdL6KBDBDqbSFep1E6+QQnkhKaF83I/OkmqsoVc=,iv:ZWVsmqEq1S7vG9IGExqs1mB6X8QM0W5f6YQFgqUZllg=,tag:iVopHbkE57AHunDOs5UtLg==,type:str]
    redis-password: ENC[AES256_GCM,data:7iPT4uYke7c6qp/rVskKKMRemJOhcZFSFbvRXxjYRCRU5DCRFCyc6dXSaR5fOHq+mAnvffw=,iv:PBh2iMSNXLLJ8rsCkKYFePKiq+wLW7OXq4JXyUjEs0k=,tag:tZgd9SZql7FURSibLWySyA==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T22:59:38Z"
    mac: ENC[AES256_GCM,data:r8bFhcgGFX9w125+C5DnPIW5rnSp4AeankuTotWwTO7haXXZiDcmeZxG2FYeuEEew6h2IKh+h8TlEvIZAD1XpUJytChQMIBBkONRHw9rzUn7ZeHzJXqVK8WgBATphdBUAQKMDJwyZxPP+Q/y7LjwhkHqwW5EuswZK7PDbP723Mw=,iv:4Wnas6qbIPFhZk770V+KbHCzPxgs88UIDEc3InpddK4=,tag:FLRTmcMUq5V7X7vkE7+y3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
