apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:GG06bRQIZCS3Hnvq9zMakMyzTnU/oAdYX2az2wObvn9UdRNaDW8ISbiHOzHxfy4=,iv:GS+0ALEq6H8W1zxHlu5HkONcW18ICoT8vrJv0gIfjE8=,tag:bdPRJVgp3kMCth7ZM7E6mA==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T16:53:10Z"
    mac: ENC[AES256_GCM,data:I+AfoII0hV13Ec9qzJmheIdMa9Y3//uZ8ce/y0x5F8L53x/KrUX9mIQ0hqrJ8ZEDMhJlZarnfaLacJUk/OXGHN0mTlcbFl06p6isNjhULMeE8wAbw7s/5sA+cWuZ48nOgAxJDknab3qfBNlgmDJfltKr6IDlozDLCuVPwOzomsw=,iv:6ID2sR5p3WopbFszZxbyBTNqq30ix7gPL1LXPOzYaRQ=,tag:zALeY8m5rOiXpIxXdX6VTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
