apiVersion: v1
kind: Secret
metadata:
    name: homarr
    namespace: homarr
type: Opaque
stringData:
    oidc-client-id: ENC[AES256_GCM,data:jh+7xgH5,iv:giCivqGnIMmyHyZvAN6Q/wpnewHMUOa/BHrzgiExPJg=,tag:7Mv3Jpo+2swDMh8FBThn+A==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:4JUCazzC44NnaUY1TCrdOfC1puTEtAXSbmRJh7Z3lZtIewel/A51AtMMCTJsK4TX6kiVncuDf0vjS7Xp/ORvGLI=,iv:yBn5MG53ng2xRlxtuuLGOW7pQN/jHd4sib/CoKy7ADY=,tag:L4fZsi7yMd8iqzAKm6bjKg==,type:str]
    bind-password: ENC[AES256_GCM,data:IpCP55mXa7acpRlNd25sKIUhrahr8SXWu+7TQb/5Wl3aXOX+avvA2EeNKvyTdLAdDKjTu2tkQO2G6oI=,iv:gs5xaBX3+GV+f05SL6VFtU0pQOwcvjRNVNIBLFhFmN4=,tag:oiWRx8GcmxKDznDu6DslFg==,type:str]
    db-encryption-key: ENC[AES256_GCM,data:T42tpOqsNUtAvNwZXn/xRHXvvKm7GHrhQd+hXbVn6J8Jb1SMOGdtAzY414qacF24s7SlltVTwQk1g90dFD/yjA==,iv:dmXekgRqUqnW3BUBAfJpWUxrpyn0KHUZG9/oY1OxLak=,tag:U+EQJz1ZrdPqgE5za9jUNg==,type:str]
    db-url: ""
    mysql-root-password: ENC[AES256_GCM,data:xqiXmzqZKsxVaSik4YdKdFGyR7oNf0dr4DffeQEl4MPHJwd1SKemcnSpzgrKUaZFBkStlm5VNACwz7hld2F6Yl6u,iv:45Q3NpNVr89CTeaett89YJOt0nUi66TiYD+9oMq/b7M=,tag:cn6kFTclwLv/GJv5kEo3gw==,type:str]
    mysql-password: ENC[AES256_GCM,data:r1u6jTOALZqpS0y1xl5epsyRmZqAYlKEbH/JYrNgCjqRoBi3zOwgZ8XRdzYwzGY/4jP3W9OCL73ou1Ke8dG6SRw=,iv:H682eeCOn8Imorq409DV1eHgntVtd0lSv+Ill9onNV8=,tag:i44zItNS1Q2QrjUk98nH1A==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:26:24Z"
    mac: ENC[AES256_GCM,data:Pyh+rhOKWPPXJ5hBBmsQgqR2swiemwg2KxmtAjBMuLDZ1TDIYzZ06wAHx8mq+2bRegRtwRvJ1DXkKiraHwYRJSJBZfR850nORPM8RzWX1H51XWO9RlT14sbl+jdmScOx1oPVIwVBBdjWlPPszX6osbhhdEnYNz1PXqcmw8/v46A=,iv:Y8bazpa1BO8JrR66Ik+wTx+YX6JwhxCZkRwquz05e80=,tag:W+ndHNG5w9/1UHdTKDSn6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
