apiVersion: v1
kind: Secret
metadata:
    name: homarr
    namespace: homarr
type: Opaque
stringData:
    oidc-client-id: ENC[AES256_GCM,data:jh+7xgH5,iv:giCivqGnIMmyHyZvAN6Q/wpnewHMUOa/BHrzgiExPJg=,tag:7Mv3Jpo+2swDMh8FBThn+A==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:KNxtkUmMk74es5tVLleN1wbLybbeZVtJuRHIPV6OkUbs2rIw3nzvaCVGjm7m/5RKoMXilgT+NlKprS8femspDQ==,iv:kqL6nLOUAnccfDrSCP2ktnKeAK7LDFD6r1A+R73CDbM=,tag:Y4Xz+kvyqy3d1auJWckawQ==,type:str]
    bind-password: ENC[AES256_GCM,data:cDvbsK3AgHiIdtH3N1Yu2vGQ4QD1xPePlbzWK6GZZztOer8bcg1npylFbZ1PMu381/y1IHwb0YZPBWx0UPp05A==,iv:5zL7mQbqbUVPyNGJPFYpGIZP6fF4c3+vVS5BcEY1MLQ=,tag:nVQ0tJgn/n6rkCCdmHDZaA==,type:str]
    db-encryption-key: ENC[AES256_GCM,data:xSiKKwQEFZCd01N+PvOp470bgEuBTluxIVUM2npMCx7Wi6lnuDf8YKM8q8SdW/PnNZ2KpOh+o6mhgG5Foe2eag==,iv:FIYFzyTA6XtcMl3NUkfudtenrFCsGFt7DQfO9srwGXA=,tag:ae2cHUrxn9dDauZnqYsBqQ==,type:str]
    db-url: ""
    mysql-root-password: ENC[AES256_GCM,data:ktGgx+4JD0gmYPCTGnJZEi44clTxeO6LqY2CXH4+yO+wWh8Z4gYMMLV/tVeYNo0efBPJUaFbBF5bjbOZ5+FF2A==,iv:ocCuTUmdmZ+1ZLx5N6tOWpRH5oObhLwbJ5NTWdNA4j4=,tag:wsSu/mW/Oyc3osOP7tKfzw==,type:str]
    mysql-password: ENC[AES256_GCM,data:TzJUA2xJg1VYGI403jLhZSwd67WwBqhjZSxb+hVp7OKg1NUHONX6Ens3NbusITOoUdbQbN0oGQwy3CrTn87KHg==,iv:hUFaHeLLIxxgUAbqEhJeBrpuSNnuLel4U1+3SoR0mPU=,tag:ddP0YiZgLqCc9rym0lk4UA==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:29:03Z"
    mac: ENC[AES256_GCM,data:V9Mor3Es7uKC5b/C2aZhQR16HXWdWj3YB+mFzOO8sicIgPO8V1nSuH4zwZPvVkE3ZccWy0mvFYtfZXGso+gtBNzX6xYabXR8I+ynssWyBNNyzYP5KTY77EerOdAL5BEyn2tlg/0JVjZCwVGuKW5brROCG86Mz+FqzqDgF9aGRug=,iv:Y+GwoyDiUdeI3CtWDxDX80JtFf5ZaSzK7OvuJ2F7EFM=,tag:cnzFMRFYIMxR3TfrGSTpVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
