apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TyfEwa+HdPHifGm9Cd3VBOMkeQreJGS9T9dm40m/PdwXplGkwT04HLZ70d8e38yzIUt0WUb8SMgdz4jLdvx3zZsgZeaZVFGFjtyrYs6bUOw3Rz+3DNiJ1c1QnPh84SGwWMn1RQvzHlkZlIdrsaZ5uVEVrEVa31Xsb11WaqutUvHiukc7LoA=,iv:b3pMuRNDBBRFOj1bFVy28dljNbDecIxMCfco5kxHoxc=,tag:krQ/azLarDzw+0v4bMiH7A==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK3lBYVZiQmsrT1p3TXRV
            Z2dkLzRWaTlWenJxcUJuZFltWHByR3JuQ3lRClcveHFvWTdySXczWVlYbyszM1Nt
            RzhXNEZIMnFFY014dW1zZDUyZEswYlUKLS0tIFk2eTB2dCtOZXppbVJuQi9aMCtC
            OVRrUWNML292VG5VMU1hWGprOWVFRnMKePOXaJ8dJ6JaYdeLGZyWaGAdlB+M93na
            SCpPLqv0mLC5nXjuUaZZr5zTKVEFiy+r77VcI3y3ptz7Q4GkiPbQ+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T05:50:22Z"
    mac: ENC[AES256_GCM,data:eZyDmI7CVcp0ldyDbZjwqR+pAtC64/svCw2yKQcAMmtMieCI5vyHl4/A5+DyA87/7GnHQ2wwKZUhSXRLM0opf8esGGQWOT+axBG0GGkno6D5c+DbIaZtMJlXRpJ5KERQKsIAPZ/HcVFJZ938zAUT4kyjSN3tb7JUMj0z+2Lvd/w=,iv:p8ByvOxe8q8F52lJqx9JAqbnwt/zhJczGDw/Qd8zn/Q=,tag:882Ku2Wigr4MRBIkYDe1OA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
