apiVersion: v1
kind: Secret
metadata:
    name: podinfo
    namespace: podinfo
type: Opaque
data:
    password: ENC[AES256_GCM,data:KuJXA+z5ATXTl+CVqTin,iv:dve5nHQl/cMMy9SY9gbUCqYu5yvRbjSNkhGlIX5/GAQ=,tag:dieO6dRTIvMdhy+IxK87aw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q215V2tMN1ZSSG1XcWl2
            MFdCL21VVy9Nby9GZlNnT2Rxd3MvcTdHUVFrCmNXVU9ZRWQ0cWg1MklFYnlTazNQ
            R0tnaGROSjFva0l0QW1aUnNKeGE5SVEKLS0tIFlWUGJwRG5QWldHUU5HcEZoQkFV
            amlHWUc2VUpweTlQQnlaMU9iQjZiVW8KSOyhUSmcQTCre4g38bNjnIYkc9Kln+32
            2A7XKxVQotCTpD4Pwcl7lKazw2Q/bdUIJd+aP3GAa+buQKGv1OOJ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T06:29:33Z"
    mac: ENC[AES256_GCM,data:0RasCYReQzjd6KFnJS0H0/m6I8cK0HjIBQmLF+Q4D7hTsBnnSxKq1q57ALnCitMc0zGegbifoOL3vhTax7GhD4JteBfwds2YlpttphWp2TY7ch+bbYgHw/CWLe5e1AM92JC9vzG9gPTZxXvbpS+ov6NNA2yZpGH1UF5vt5sJ92g=,iv:+IDqlUPl24AS3ms7DPz0KJjUe+ZXI+plgT0Q/9hBe2k=,tag:IkLozKR6MTogdwBOkTXIPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
