apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: servarr
  namespace: servarr
spec:
  interval: 5m
  chart:
    spec:
      chart: servarr
      version: "1.1.7"
      sourceRef:
        kind: HelmRepository
        name: servarr
        namespace: flux-system
  values:
    jellyfin:
      persistence:
        media:
          existingClaim: "servarr-jellyfin-media"
          accessMode: ReadWriteMany
          size: 300Gi
      image:
        tag: "latest"
    sonarr:
      env:
        TZ: "Europe/Berlin"
      image:
        tag: "latest"
    qbittorrent:
      env:
        TZ: "Europe/Amsterdam"
      image:
        tag: "latest"
    prowlarr:
      env:
        TZ: "Europe/Berlin"
      image:
        tag: "latest"
    bazarr:
      env:
        TZ: "Europe/Berlin"
      image:
        tag: "latest"
    radarr:
      env:
        TZ: "Europe/Berlin"
      image:
        tag: "latest"
    lidarr:
      enabled: false
    readarr:
      enabled: false
    cleanuperr:
      enabled: true
      image:
        tag: "latest"
      secrets:
        existingSecret: "servarr"
      env:
        TZ: "Europe/Berlin"
    jellyseerr:
      image:
        tag: "latest"
