apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-jellyfin-media-pv
  namespace: servarr
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media-library
    server: 100.97.177.7
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-jellyfin-media
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  volumeName: servarr-jellyfin-media-pv
  storageClassName: ""
