apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  namespace: jellyfin
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media-library
    server: 100.97.177.7
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  volumeName: media-library-pv
  storageClassName: ""
