apiVersion: v1
kind: Secret
metadata:
    name: servarr
    namespace: servarr
type: Opaque
stringData:
    QBITTORRENT__USERNAME: ENC[AES256_GCM,data:X8VMDfQ=,iv:HVx7vYirB2GxzfWHxRPygBe59HBYHO8PpsLRbPgBdlY=,tag:LYSAIw4jlsXsyN9s6XFWww==,type:str]
    QBITTORRENT__PASSWORD: ENC[AES256_GCM,data:oJZM93M=,iv:H04ulcViNkLPrscdYNTtKQtta/+rylnoKKjK0Y2SDno=,tag:+LMU+vaFLnFZtn4Cs8gErQ==,type:str]
    SONARR__INSTANCES__0__APIKEY: ENC[AES256_GCM,data:bicwiQ==,iv:V6xRf4+4u3KLTAWdeAIInLbOX8Hu/6i+JalR4o8HI3c=,tag:HGMSMmMe4mlW44QrkQQCuQ==,type:str]
    RADARR__INSTANCES__0__APIKEY: ENC[AES256_GCM,data:8k6nzw==,iv:ap662K+IZbYNXIlXfC0hI2+05XOBN+Orlp6wDX9o7V0=,tag:wQAD21P/jr3X6nRHbU052Q==,type:str]
    LIDARR__INSTANCES__0__APIKEY: ENC[AES256_GCM,data:ukcUkg==,iv:DnJt7v7BZcWhZf29WabwtIPrXPb6Zm+zPHGrxioU86g=,tag:KMYHbbweQ50IQW9DjOascw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T18:54:14Z"
    mac: ENC[AES256_GCM,data:ZBaxKBmluK0lsj7zOzePLJrLmQkbFqMg+GwQsTH61eAuu3hRZfSA2sKY5v6TDFGlz/iTCzc7oYhon9YEEz1ee77tffFxBoDGmOmqkOqMTwSEl6pOXMaus6qYpoIxsX+6CJ/ozQo9u5hmkKwKkTdR9GhCMRzvAy8o2g4i69yo3Xo=,iv:xSvfz5PLfmcT0CXqP7Nk4/P/3MRBoXdKkksjqCQXUB0=,tag:+wMAnOw/tOFOh5tIfEyhTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
