apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
  namespace: ocis
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/ocis
      version: ">=0.7.0"
      sourceRef:
        kind: GitRepository
        name: ocis
        namespace: flux-system
  values:
    externalDomain: owncloud.wild-fahrenheit.ts.net

    features:
      sharing:
        passwordPolicies:
          minCharacters: 12

    secretRefs:
      adminUserSecretRef: admin-user

    services:
      idm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOncePod
          size: 10Gi

      nats:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOncePod
          size: 10Gi

      ocm:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOncePod
          size: 1Gi

      search:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOncePod
          size: 10Gi

      storagesystem:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 5Gi

      storageusers:
        events:
          consumer:
            concurrency: 10
        storageBackend:
          driver: ocis
          driverConfig:
            ocis:
              maxConcurrency: 100
            s3ng:
              maxConcurrency: 100
              endpoint:
              region: default
              bucket:
              disableContentSHA256: false
              putObject:
                disableMultipart: false
                sendContentMD5: true
                concurrentStreamParts: true
                numThreads: 4
                partSize: 0
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 50Gi

      thumbnails:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi

      web:
        config:
          apps:
            - files
            - search
            - text-editor
            - pdf-viewer
            - external
            - admin-settings
            - epub-reader
            - preview
            - ocm
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
