apiVersion: v1
kind: Secret
metadata:
    name: ldap-secret
    namespace: ocis
type: Opaque
data:
    reva-ldap-bind-password: ENC[AES256_GCM,data:rGy7lM7yPKTL1YnZ9ujd1GsW8pbkgi6B4++PPqrPSQtFfVYw,iv:OMHRDmbvMfqEKzQKd73wnQ1EW+EHdZ1X8eOeNygJD5Q=,tag:KiMlEMLcWLKgDaWM8cj7iw==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MUlDb3QwSFI3ckt4enFx
            Q0poVXgzaXdjczFmMHlSSGJuUWZ3eGFRdkcwCmtoLzVJRkExWnltbXh2eXNmTWY3
            ZTQ3WCtYckZ1aGoxam55WitpalNEWFkKLS0tIDQwR1FEV0dQQ3hqaTIwVW9KVGRw
            OHBRNVFWa2lBcHZxSnFSZTMwNmczRDgKBUUKxDgzdMowgOnq8uevXnzG38MTOqst
            AhTwl+6DjUfa/QZJkLmlsWq59RYLmd4GWg6bOFHjSVuJjm0qCHEmIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T01:40:32Z"
    mac: ENC[AES256_GCM,data:EGL1WTWwJckX+xzNLPMhjIfdwh9gF8+VOtIQKN9MKFViFyd1TZgtMQaYSAepGRdcuujIqVUhHU2wl5ww3ylP3bAS1UfFT9d7HvcrO1Pbfn3Ji42otByuQWCNYxllltsyqT9I9/p0b40SOOdKl2zRhlEF/QUBzaPcjoegXs9LLVA=,iv:4RuNLil0KGU5TU+XD+ILMiEmHEtVfQXwyPWozBzkpt4=,tag:bv+/waQ/eh68/PoyAL2WjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
