apiVersion: v1
kind: Secret
metadata:
    name: ldap-secret
    namespace: ocis
type: Opaque
stringData:
    reva-ldap-bind-password: ENC[AES256_GCM,data:ppbvkc2a4n+t/2NXsddgI/8WAHWHMAGEObCD18bCfyGWm01O,iv:5hxhe6mGpt0AXtAMeRGwmJXJTItwjkvMk9AbGIEqmMQ=,tag:eR5YF+LBgKyIS/IQlT9LrQ==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUmFuUUl5aHowdkIzdDBK
            Vy9DelljZUoydjlxUDBWUUYxVmU0SWJWYVJVCnZDWWNUVitGekxQck0yRG42NVcv
            QU9FUUlqVXdsbmJDQnY3aHlDdjVtd2MKLS0tIFBtbjZ3RHhBdytQWTZ5RnY5UlI1
            SmNsYjJhWlJiM1RVdmlDNTNRVllhY3MKXKqdZVq6nvEqogvntZGoGYnzAwg/9WxM
            XYqDEsGwgnM2TGvH8TTsf7W7yxmRg6M4N5rnXZcabgTDFqRpb7Fi1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T03:43:50Z"
    mac: ENC[AES256_GCM,data:zncfU5bX3sFO3GToWc4X21/ebcAApi85+EgZ+O3sZmGSzAThA0QlU9+kw9IIXBYu5QcCjZsqwPwpeD3uF+fqDSzOiU94NjoF6tpu/5x3VTUKuorUewmErjKfq/bPRxlX7XsY88GqOiA12++dgVtVfQZrvoikumM/6bMeg6SMFYg=,iv:0Ml7sQH/ibz49ZVjIKxCPkyLeYgDB+s5rp2VP6UGQ0Y=,tag:zKGmHrLiq04DSJAo7UMuJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
