apiVersion: v1
kind: Secret
metadata:
    name: ldap-secret
    namespace: ocis
type: Opaque
data:
    reva-ldap-bind-password: ENC[AES256_GCM,data:Q20tQOEDFUKEhBzKWZP5wiuqjmNqSAmAVsDJU7Q2mZdaruXG,iv:SKqw3LPvGz92eAHoxhJoKI56G0kgNySPRFy4nx9zVTk=,tag:FbU/543EEKQpxPFEiV7iMQ==,type:str]
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaWU3M2pXQlU2VXM0aDZG
            MTlMWjdoZFFQdWZNQXI0VTMzRWhub0lRTkRzCmM1cUd0NVJJRHdscmxxa2t2cXZw
            U2I4dG9GNkQra0FxUHNQZ05qUHNXT2MKLS0tIHZ3ZXo2a0UrdXhsaXFJZ2N1Q2VS
            R01raHNqYWdDN1JPbERYN01RbVhkN0kKKP/NEt4ZUuPkmbOtYkCNieOi2ZWsL835
            Bo6GqGC6usj5Tdc50krHI/V7pOU9JTITom3L1SHGWV+HH0fiDqBXvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T01:25:16Z"
    mac: ENC[AES256_GCM,data:F3w2Zb/9nqwJj48eJ+pkt+Ix/x077NwsTkDxIg98L9Ocawbvpat1KBrsrLiSIStFis2knj8gYuWb/9JD0j36LtEDI+8r9kc46j5gTgp7M7hNk0YctHwS0+qDiaa36ZhaA1XLyPanGKbDNpnGH0aRxDirfnOVOu46KuwtlRNGrhM=,iv:KOOiF9vEqTxKeII82phyFtcfBUPCyJ/k/WWmpJLukkU=,tag:+AkzEKOG51K3E2+8BekC4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
