apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: davmail
  namespace: davmail
spec:
  interval: 5m
  chart:
    spec:
      chart: davmail
      version: ">=0.1.0"
      sourceRef:
        kind: OCIRepository
        name: davmail
        namespace: flux-system
