apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: davmail-ingress
  namespace: davmail
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: davmail
      port:
        number: 1080
  tls:
  - hosts:
    - davmail
