apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ebLzdgyRuyN5s1Fy,iv:AHPUg3zO4H9LUMQoanxNnkkrr/tOKCGuvWr5PBKVabU=,tag:fD7aq884madS55sleiWbyw==,type:str]
kind: Secret
metadata:
    name: podinfo-password
    namespace: podinfo
type: Opaque
sops:
    age:
        - recipient: age18ef0t9rgwe9gth0080hhv6zupu4fu64ugfplgjcx9lv4ev8ya9lqyystv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtalpiVHAvdjhSWUIrVWow
            U29sR2Q1a2w0Q0N5MVFhNXBKWElsVWxQTVRvCi9aNkVVZU5EcDY4SXRCdGx5WVNm
            SysrTjM3bnl3a2tYVGhCaUkrV3F2ZU0KLS0tIDVKSkN6Vkd1VnNvdEc1QmdoZ2FU
            NWN5cWRUVzJiZzBLcUxVYUlYSWtzWjgKpaaH0336rT+vdROMZB+SRo8QYSmAiHkY
            gwobfDxShTPjHIKPk9HEDrHEuHHMaiHIgTn5f9h//lDkcmgVdeoNEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T11:04:53Z"
    mac: ENC[AES256_GCM,data:XpQfeOsX3zHdRXmDfbG8NOxMPI2BdcsK+XItBs1aZCM2ywBmfmAH+FjUsk1NKEK3nO5JzRHJfG10ntBBzCvrDbbjsFCItDYloEEAHIsynlKh++C6Vy+yLT9E+Ow1pu4UYDiFlrt0y2QMsDRAzVmvWzYYBkNka6H4oznnDMd0c5s=,iv:V0T01U1L//k2hcTmU6p7lCD0KwOhnnXXMODe4Y6UI5M=,tag:gSqXPpv0QNYioKQo9a1ORA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
